config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'following' => 'epicenter#following'

  get 'followers' => 'epicenter#followers'

  get 'all_users' => 'epicenter#all_users'

  get 'retweet' => 'tweets#retweet'

  resources :tweets
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user


	has_many :tweet_tags
	has_many :tags, through: :tweet_tags

	validates :message, presence: true
	validates :message, length: { maximum: 1000 }
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
	belongs_to :tweet
	belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets

  mount_uploader :avatar, AvatarUploader

  serialize :following, Array

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username, :bio, :location, :avatar, :following])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username, :bio, :location, :avatar, :following])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

	before_filter :authenticate_user!

  def feed
    @tweet = Tweet.new

    @followercount = 0
    User.all.each do |u|
      if u.following.include?(current_user.id)
        @followercount += 1
      end
    end

  	@following_tweets = []

  	Tweet.all.order('created_at DESC').each do |tweet|

  		if current_user.following.include?(tweet.user_id) || tweet.user_id == current_user.id
  			@following_tweets.push(tweet)
  		end
  	end
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end


  def show_user
  	@user = User.find(params[:id])
  end

  def now_following
  	current_user.following.push(params[:id].to_i)
  	current_user.save
  	redirect_to :back
  end

  def unfollow
  	current_user.following.delete(params[:id].to_i)
  	current_user.save
  	redirect_to :back
  end

  def following
    @users = []

    User.all.each do |user|
      if current_user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @users = []

    User.all.each do |user|
      if user.following.include?(current_user.id)
        @users.push(user)
      end
    end
  end

  def all_users
    @users = User.all
  end




end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  include TweetsHelper


  def retweet
    Tweet.creat(message: "", user_id: current_user.id, retweet: true, retweet_id: params[:id])
    redirect_to :back
  end

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end




  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :retweet, :retweet_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

	def get_tagged(tweet)
		message_arr = tweet.message.split

		punctuation = %w(. , ? ! ; - : & *)
		temp_word = ""

    message_arr.each_with_index do |word, index|
      if word[0] == "#"
      	temp_word = word
      		if punctuation.include?(temp_word[-1])
      		temp_word = temp_word[0...-1]
      		end
        	if Tag.pluck(:phrase).include?(temp_word)
          	tag = Tag.find_by(phrase: temp_word)
        	else
          	tag = Tag.create(phrase: temp_word)
       	end  
       tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
       message_arr.delete(word)
       message_arr[index] = "<a href=' /tag_tweets?id=#{tag.id}'>#{word}</a>"
      end
    end

    tweet.message = message_arr.join(" ")
    return tweet
  end
end

app/views/epicenter/_current_user_stats.html.erb
<div class="col-md-4 divback">
	<div class="row">
		<div class="col-md-2">
			<%= image_tag current_user.avatar.url, width: "50" %>
		</div>
		<div class="col-md-10">
			<p><%= link_to "@#{current_user.username}", show_user_path(id: current_user.id), class: "no-underline" %></p>
		</div>
	</div>
	<div class="row center-it">
		<div class="col-md-4">
			Comments
		</div>
		<div class="col-md-4">
			Following
		</div>
		<div class="col-md-4">
			Followers
		</div>
	</div>
	<div class="row center-it">
		<div class="col-md-4">
			<%= link_to current_user.tweets.count, show_user_path(id: current_user.id), class: "no-underline" %>
		</div>
		<div class="col-md-4">
			<%= link_to current_user.following.count, following_path(id: current_user.id), class: "no-underline" %>
		</div>
		<div class="col-md-4">
			<%= link_to @followercount, followers_path(id: current_user.id), class: "no-underline" %>
		</div>
	</div>
</div>

app/views/epicenter/_users.html.erb
<% @users.each do |user| %>
	<div class="col-md-4">
		<div class="well">
			<div class="row">
				<div class="col-md-6">
					<%= image_tag user.avatar.url, class: "mini-pic" %>
				</div>
				<div class="col-md-6">
					<% if user.id != current_user.id %>
						<p>
							<% if current_user.following.include?(user.id) %>
								<%= link_to "Following", unfollow_path(id: user.id), class: "unfollow_btn  btn btn-success" %>
							<% else %>
								<%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
							<% end %>
						</p>
					<% end %>
				</div>
			</div>
			<p><%= link_to "@#{user.username}", show_user_path(id: user.id) %> <% if user.following.include?(current_user.id) %> <span class="grey-text">FOLLOWS YOU</span> <% end %></p>
			<p>
				<%= user.bio %>
			</p>

		</div>
	</div>
<% end %>

app/views/epicenter/_userstats.html.erb
<div class="col-md-3">
	<p><%= link_to "@#{@user.username}", show_user_path(id: @user.id) %></p>
	<p><%= @user.bio %></p>
	<p><i class="fa fa-map-marker"></i> <%= @user.location %></p>
	<p><i class="fa fa-calendar"></i> Joined <%= @user.created_at.strftime("%B %Y") %></p>
	<% if @user.id != current_user.id %>
		<p>
			<% if current_user.following.include?(@user.id) %>
				<%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
			<% else %>
				<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
			<% end %>
		</p>
	<% end %>
</div>

app/views/epicenter/all_users.html.erb
<%= render 'users' %>

app/views/epicenter/feed.html.erb
<body class="bioRhyme">
<div class="row">
	<%= render 'current_user_stats' %>
	<div class="col-md-7 col-md-offset-1">
		<div class="row new-tweet-area">
			<div class="col-md-1">
				<%#= image_tag current_user.avatar.url, class: "mini-pic" %>
			</div>
			<div class="col-md-11 mtop-6">
				 <%= render 'tweets/form', tweet: @tweet %>
			</div>
		</div>
		<div class="row">
			<% @following_tweets.each do |tweet| %>
				<div class="col-md-12 tweet-area borderline">
					<p>
						<%= link_to show_user_path(id: tweet.user.id), class: "no-underline" do %>
							 <%= "@#{tweet.user.username}" %>
						<% end %>
						&#8226; <%= time_ago_in_words(tweet.created_at) %>
					</p>
					<p><%= tweet.message.html_safe %></p>
			
				</div>
			<% end %>
		</div>
	</div>
</div>
</body>

app/views/epicenter/followers.html.erb
<%= render 'users' %>

app/views/epicenter/following.html.erb
<%= render 'users' %>

app/views/epicenter/show_user.html.erb
<h1 class="bioRhyme">@<%= @user.username %>'s Profile</h1>

<p class="bioRhyme"><%= @user.name %></p>
<p class="bioRhyme"><%= @user.location %></p>
<p class="bioRhyme"><%= @user.bio %></p>

<% if @user.id != current_user.id %>
	<p class="bioRhyme">
		<% if current_user.following.include?(@user.id) %>
			<%= link_to "Unfollow", unfollow_path(id: @user.id), class: "btn btn-success unfollow_btn" %>
		<% else %>
			<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
		<% end %>
	</p>
<% end %>

<div class="bioRhyme">
	<% @user.tweets.each do |tweet| %>
		<div>
			<p>@<%= tweet.user.username %></p>
			<p><%= tweet.message %></p>
		</div>
	<% end %>
</div>

app/views/epicenter/tag_tweets.html.erb
<body class="bioRhyme">
	
<div class="center-it tag-topic-header">
    <h1><%= @tag.phrase %></h1>
</div>

<div class="row">
    <div class="col-md-7 col-md-offset-1">
			<div class="row">
	    	<% @tag.tweets.order(created_at: :desc).each do |tweet| %>
	    	<div class="col-md-12 tweet-area borderline">
				   <p>
				   	 <%= link_to image_tag 'yoshi.png' %>
				     <%= link_to show_user_path(id: tweet.user.id) do %> 
					   	<%= tweet.user.name %> <span class="no-underline">
		         	<%= "@#{tweet.user.username}" %></span>
				     <% end %>
			  		&#8226; <%= time_ago_in_words(tweet.created_at) %>
				   </p>
				   <p><%= tweet.message.html_safe %></p>
				</div>
	    <% end %>
			</div>
    </div>
</div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title class="bioRhyme">Warborn Angels Wall</title>

    <%= favicon_link_tag 'favicon.ico' %>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bioRhyme">
  	
  	<nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Main chat page", root_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Angel List", all_users_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Write New Comment", new_tweet_path %></li>
            <% end %>
          </ul>
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag current_user.avatar.url, class: "navbar-pic" %> <%= current_user.username %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>

    <div class="container">
	    <%= yield %>
  	</div>

  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :message, placeholder: "What's happening?", class: "form-control" %>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= f.button(class: "btn btn-info") do %>
      <i class="fa fa-pencil-square-o"></i> Comment
    <% end %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<body class="bioRhyme">
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user_id %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_tweet_path %>

</body>

app/views/tweets/new.html.erb
<h1>New Comment</h1>

<%= render 'form', tweet: @tweet %>

app/views/tweets/show.html.erb
<body class="bioRhyme">
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

</body>